[functions]
  external_node_modules = ["express",'body-parser','cors','swisseph','serverless-http']
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"